<div itemscope="" itemtype="http://developers.google.com/ReferenceObject">
<p><meta itemprop="name" content="tf.random.experimental.set_global_generator" /> <meta itemprop="path" content="Stable" /></p>
</div>
<a name="//apple_ref/cpp/Function/tf.random.experimental.set_global_generator" class="dashAnchor"></a><h1 id="tf.random.experimental.set_global_generator">tf.random.experimental.set_global_generator</h1>
<p>Replaces the global generator with another <code>Generator</code> object.</p>
<h3 id="aliases">Aliases:</h3>
<ul>
<li><code>tf.compat.v1.random.experimental.set_global_generator</code></li>
<li><code>tf.compat.v2.random.experimental.set_global_generator</code></li>
<li><code>tf.random.experimental.set_global_generator</code></li>
</ul>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">tf.random.experimental.set_global_generator(generator)</code></pre></div>
<p>Defined in <a href="/code/stable/tensorflow/python/ops/stateful_random_ops.py"><code>python/ops/stateful_random_ops.py</code></a>.</p>
<!-- Placeholder for "Used in" -->
<p>This function creates a new Generator object (and the Variable object within), which does not work well with tf.function because (1) tf.function puts restrictions on Variable creation thus reset_global_generator can't be freely used inside tf.function; (2) redirecting a global variable to a new object is problematic with tf.function because the old object may be captured by a 'tf.function'ed function and still be used by it. A 'tf.function'ed function only keeps weak references to variables, so deleting a variable and then calling that function again may raise an error, as demonstrated by random_test.py/RandomTest.testResetGlobalGeneratorBadWithDefun .</p>
<h4 id="args">Args:</h4>
<ul>
<li><b><code>generator</code></b>: the new <code>Generator</code> object.</li>
</ul>
